### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by jerryfree** [ajrnz/scemplate#1]
when i import the scemplate to my project using   
libraryDependencies += "com.github.ajrnz" %% "scemplate" % "0.5.1"
there comes error

[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.ajrnz:scemplate_2.13:0.5.1
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\jerry\.ivy2\local\com.github.ajrnz\scemplate_2.13\0.5.1\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/ajrnz/scemplate_2.13/0.5.1/scemplate_2.13-0.5.1.pom
[error]   not found: http://maven.aliyun.com/nexus/content/groups/public/com/github/ajrnz/scemplate_2.13/0.5.1/scemplate_2.13-0.5.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/github/ajrnz/scemplate_2.13/0.5.1/scemplate_2.13-0.5.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/github/ajrnz/scemplate_2.13/0.5.1/scemplate_2.13-0.5.1.pom

**Comment by ajrnz** [comment]
sorry you need to use version 0.5.2 for scala 2.13

I've updated the docs

**Comment by jerryfree** [comment]
Great,thanks
